### ISSUE TITLE
MacOS crash System.NotImplementedException

### ISSUE THREAD

**Issue by admiraldaro** [MustaphaTR/Romanovs-Vengeance#102]
OpenRA engine version aa077b4
Red Alert 2: Romanov's Vengeance mod version playtest-20221009
on map 4201fa5f5b74ca6b88d58d412ae710475d307177 (DC Uprising by Westwood Studios).
Date: 2022-12-30 23:00:11Z
Operating System: OSX (Unix 11.7.1)
Runtime Version: .NET CLR 6.0.9
Exception of type `System.NotImplementedException`: No rules definition for unit cathosp
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Actor.cs:line 144
   at OpenRA.Mods.Common.Traits.SpawnMapActors.WorldLoaded(World world, WorldRenderer wr) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/World/SpawnMapActors.cs:line 49
   at OpenRA.World.LoadComplete(WorldRenderer wr) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/World.cs:line 288
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 203
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/UnitOrders.cs:line 154
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 168
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 347
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 636
   at OpenRA.Game.LogicTick() in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.Loop() in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 820
   at OpenRA.Game.Run() in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

**Comment by MustaphaTR** [comment]
Fixed, for the time being you can download and use this version of the map: https://resource.openra.net/maps/49679/
