### ISSUE TITLE
cyur120.wav is not a valid sound file

### ISSUE THREAD

**Issue by segatrade** [MustaphaTR/Romanovs-Vengeance#105]
Got this:
```OpenRA engine version aa077b4
Red Alert 2: Romanov's Vengeance mod version playtest-20221009
on map e499afcea76cbfd0c938a342dca87e0f62895933 (Official Tournament Map (8) by Westwood Studios).
Date: 2023-05-11 12:19:20Z
Operating System: Linux (Unix 5.19.0.41)
Runtime Version: .NET CLR 6.0.9
Exception of type `System.IO.InvalidDataException`: cyur120.wav is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 82
   at OpenRA.Sound.<>c__DisplayClass15_0.<Initialize>b__1(String filename) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 98
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 355
   at OpenRA.Sound.PlayNotification(Ruleset rules, Player player, String type, String notification, String variant) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 444
   at OpenRA.Mods.Common.Traits.StartGameNotification.OpenRA.Traits.IWorldLoaded.WorldLoaded(World world, WorldRenderer wr) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/World/StartGameNotification.cs:line 50
   at OpenRA.World.LoadComplete(WorldRenderer wr) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/World.cs:line 288
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 203
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/UnitOrders.cs:line 154
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 168
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 347
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 636
   at OpenRA.Game.LogicTick() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 651
   at OpenRA.Game.Loop() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 820
   at OpenRA.Game.Run() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 873
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 308
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32
```

```
OpenRA engine version 6ea4490
Red Alert 2: Romanov's Vengeance mod version playtest-20220707
on map e499afcea76cbfd0c938a342dca87e0f62895933 (Official Tournament Map (8) by Westwood Studios).
Date: 2023-05-11 12:30:05Z
Operating System: Linux (Unix 5.19.0.41)
Runtime Version: .NET CLR 6.0.6
Exception of type `System.IO.InvalidDataException`: brainfre.wav is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 82
   at OpenRA.Sound.PlayMusic(MusicInfo m, Boolean looped) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 251
   at OpenRA.Sound.PlayMusicThen(MusicInfo m, Action then) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 237
   at OpenRA.Mods.Common.Traits.MusicPlaylist.Play() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/World/MusicPlaylist.cs:line 165
   at OpenRA.Mods.Common.Traits.MusicPlaylist.OpenRA.Traits.IWorldLoaded.WorldLoaded(World world, WorldRenderer wr) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/World/MusicPlaylist.cs:line 107
   at OpenRA.World.LoadComplete(WorldRenderer wr) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/World.cs:line 288
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 200
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/UnitOrders.cs:line 154
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 177
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 347
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 622
   at OpenRA.Game.LogicTick() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 637
   at OpenRA.Game.Loop() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 802
   at OpenRA.Game.Run() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 855
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 294
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32
```

```
OpenRA engine version dea9d5d
Red Alert 2: Romanov's Vengeance mod version release-20220209
on map c40bd7a4170b756a06128608631c6945c754d4c3 (A Path Beyond 2 by Westwood Studios).
Date: 2023-05-11 12:35:24Z
Operating System: Linux (Unix 5.19.0.41)
Runtime Version: .NET CLR 6.0.2
Exception of type `System.IO.InvalidDataException`: drok.wav is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 82
   at OpenRA.Sound.PlayMusic(MusicInfo m, Boolean looped) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 250
   at OpenRA.Sound.PlayMusicThen(MusicInfo m, Action then) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sound/Sound.cs:line 236
   at OpenRA.Mods.Common.Traits.MusicPlaylist.Play() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/World/MusicPlaylist.cs:line 165
   at OpenRA.Mods.Common.Traits.MusicPlaylist.OpenRA.Traits.IWorldLoaded.WorldLoaded(World world, WorldRenderer wr) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/World/MusicPlaylist.cs:line 107
   at OpenRA.World.LoadComplete(WorldRenderer wr) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/World.cs:line 275
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 200
   at OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/UnitOrders.cs:line 138
   at OpenRA.Network.OrderManager.ReceiveImmediateOrders(Int32 clientId, OrderPacket orders) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 170
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 344
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 623
   at OpenRA.Game.LogicTick() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 638
   at OpenRA.Game.Loop() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 803
   at OpenRA.Game.Run() in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 856
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 294
   at OpenRA.Launcher.Program.Main(String[] args) in /home/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32
 ```

**Comment by segatrade** [comment]
Used other iso and fixed. Seems problem in content files
