### ISSUE TITLE
Crash on OSX - M1 Air - Sequoia 15.0

### ISSUE THREAD

**Issue by HamstringAssassin** [MustaphaTR/Romanovs-Vengeance#123]
Heyas, getting a crash on launch after adding content files to `Library/Application Support/OpenRA/Content/ra2/` 
Downloaded the latest release playtest.
Crashlog below... 

OpenRA engine version 3015bcd
OpenRA Language: en
Red Alert 2: Romanov's Vengeance mod version playtest-20240218
Date: 2024-10-04 19:25:18Z
Operating System: OSX (Arm64, Unix 15.0.0)
Runtime Version: .NET CLR 6.0.26
Installed Language: en (Installed) en (Current) en (Current UI)
Exception of type `System.IO.FileNotFoundException`: File not found: mousepal.pal
   at OpenRA.FileSystem.FileSystem.Open(String filename) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/FileSystem/FileSystem.cs:line 202
   at OpenRA.Mods.Common.Traits.PaletteFromFileInfo.OpenRA.Traits.IProvidesCursorPaletteInfo.ReadPalette(IReadOnlyFileSystem fileSystem) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Palettes/PaletteFromFile.cs:line 55
   at OpenRA.Graphics.CursorProvider.<>c__DisplayClass2_0.<.ctor>b__4(String p) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Graphics/CursorProvider.cs:line 42
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at OpenRA.Graphics.CursorProvider..ctor(ModData modData) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Graphics/CursorProvider.cs:line 39
   at OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/ModData.cs:line 131
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 484
   at OpenRA.Game.Initialize(Arguments args) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 440
   at OpenRA.Game.InitializeAndRun(String[] args) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 309
   at OpenRA.Launcher.Program.Main(String[] args) in /Users/runner/work/Romanovs-Vengeance/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

**Comment by HamstringAssassin** [comment]
Solved! I used files from The Ultimate Collection and it seemed to work.
