### ISSUE TITLE
Crash when opening Asset Browser

### ISSUE THREAD

**Issue by ThebestkillerTBK** [MustaphaTR/Romanovs-Vengeance#60]
I downloaded many archives and found the bad update.
I found b738e5a Broke the game

When I tried to open asset browser, the game crashed.
Here's the log file
```
OpenRA engine version e7c65ba
Red Alert 2: Romanov's Vengeance mod version e7c65ba
on map 29c0d7f33a549a80edd69ea3f99136698edeb704 (Ural Shellmap by Westwood Studios).
Date: 2021-02-12 16:34:06Z
Operating System: Windows (Microsoft Windows NT 10.0.17763.0)
Runtime Version: .NET CLR 5.0.1
Exception of type `System.InvalidOperationException`: Cannot locate type: VqaPlayerWidget
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\ObjectCreator.cs:line 114
   at OpenRA.WidgetLoader.NewWidget(String widgetType, WidgetArgs args) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\WidgetLoader.cs:line 82
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\WidgetLoader.cs:line 49
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\WidgetLoader.cs:line 67
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\WidgetLoader.cs:line 67
   at OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\WidgetLoader.cs:line 43
   at OpenRA.Widgets.Ui.OpenWindow(String id, WidgetArgs args) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\Widget.cs:line 62
   at OpenRA.Game.OpenWindow(String widget, WidgetArgs args) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Game.cs:line 128
   at OpenRA.Mods.Common.Widgets.Logic.MainMenuLogic.<>c__DisplayClass11_0.<.ctor>b__13() in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Mods.Common\Widgets\Logic\MainMenuLogic.cs:line 136
   at OpenRA.Mods.Common.Widgets.ButtonWidget.<.ctor>b__42_5(MouseInput _) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Mods.Common\Widgets\ButtonWidget.cs:line 83
   at OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Mods.Common\Widgets\ButtonWidget.cs:line 181
   at OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\Widget.cs:line 395
   at OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Widgets\Widget.cs:line 121
   at OpenRA.DefaultInputHandler.<>c__DisplayClass5_0.<OnMouseInput>b__0() in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Input\InputHandler.cs:line 50
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Sync.cs:line 190
   at OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Input\InputHandler.cs:line 51
   at OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, Nullable`1 lockedMousePosition) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Platforms.Default\Sdl2Input.cs:line 137
   at OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Platforms.Default\Sdl2PlatformWindow.cs:line 447
   at OpenRA.Renderer.EndFrame(IInputHandler inputHandler) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Renderer.cs:line 271
   at OpenRA.Game.RenderTick() in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Game.cs:line 743
   at OpenRA.Game.Loop() in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Game.cs:line 845
   at OpenRA.Game.Run() in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Game.cs:line 864
   at OpenRA.Game.InitializeAndRun(String[] args) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Game\Game.cs:line 274
   at OpenRA.Launcher.Program.Main(String[] args) in E:\code\Romanovs-Vengeance-master\engine\OpenRA.Launcher\Program.cs:line 30
```

**Comment by ThebestkillerTBK** [comment]
#61
