### ISSUE TITLE
Game Crash: [manjaro] bomberbomb.shp missing

### ISSUE THREAD

**Issue by theodoreOnzGit** [MustaphaTR/Romanovs-Vengeance#75]
Hello there,

not sure if this is the right place to raise the bug,

I installed romanov's vengance and also origin (via lutris) on linux manjaro.
I then installed red alert II and copied all the mix files into.
~/.config/openra/Content/ra2/

https://github.com/OpenRA/ra2/wiki

Now most of the time the game plays okay. But lately i have been getting this crash message.

It appears i have a missing asset for some reason.

Exception of type `System.IO.FileNotFoundException`: File not found: bits\projectiles\bomberbomb.shp
   at OpenRA.Mods.Common.Graphics.FileNotFoundSequence.OpenRA.Graphics.ISpriteSequence.get_Tick() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 110
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Graphics/Animation.cs:line 122
   at OpenRA.Graphics.Animation.PlayRepeating(String sequenceName) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Graphics/Animation.cs:line 137
   at OpenRA.Mods.Common.Projectiles.GravityBomb..ctor(GravityBombInfo info, ProjectileArgs args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Projectiles/GravityBomb.cs:line 90
   at OpenRA.Mods.Common.Projectiles.GravityBombInfo.Create(ProjectileArgs args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Projectiles/GravityBomb.cs:line 56
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass34_0.<FireBarrel>b__2() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 330
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target& target, Barrel barrel) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 326
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target& target) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 259
   at OpenRA.Mods.Common.Traits.AttackBomber.OpenRA.Traits.ITick.Tick(Actor self) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Air/AttackBomber.cs:line 70
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/TraitDictionary.cs:line 313
   at OpenRA.World.Tick() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/World.cs:line 429
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 628
   at OpenRA.Game.LogicTick() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 643
   at OpenRA.Game.Loop() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 810
   at OpenRA.Game.Run() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 863
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 295
   at OpenRA.Launcher.Program.Main(String[] args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

The mix files i copied over are as follows:

expandmd01.mix  
language.mix  
maps02.mix    
movies01.mix  
movmd03.mix  
multi.mix  
ra2.mix      
theme.mix
langmd.mix      
maps01.mix    
mapsmd03.mix  
movies02.mix  
multimd.mix  
ra2md.mix  
thememd.mix  
wdt.mix

Is there some mix file missing, or have the archives been altered? Or is there a better way to install Romanov's Vengance?

**Comment by MustaphaTR** [comment]
That's a custom artwork used for B2 projectiles, and the file is there https://github.com/MustaphaTR/Romanovs-Vengeance/blob/master/mods/rv/bits/projectiles/bomberbomb.shp I can confirm that it works fine on my end.

This was added after the last playtest, so i assume you are running the dev version. Can you check if the file is actually there for you? If not i would recommend you to reinstall. I also thought it maybe case sensitivity issue as you are on Linux, but filename and what is written in the code both seems to be full lowercase, so i don't think that's it.

Also you don't need all those mixes, only what is listed in the [wiki ](https://github.com/MustaphaTR/Romanovs-Vengeance/wiki/Manual-Content-Installation) are needed/used.

**Comment by theodoreOnzGit** [comment]
Hello MustaphaTR,

Yes i'm running dev version, i did a git pull and did the make again.

I also checked the directory listed, and when i ran ls, this is what i got:

160mm.shp       camslup.shp     grenade.shp     litningredthicc.shp  litningupg.shp  pod.shp         subt.shp     v3mslup.shp
bomberbomb.shp  empbomb50p.shp  leaflet.shp     litning.shp          nbomb.shp       ra1patriot.shp  txgasp.shp   web2.shp
camsldn.shp     empbomb.shp     litningred.shp  litningthicc.shp     parabomb.shp    scrlitning.shp  v3msldn.shp  zbomb.shp

The bomberbomb.shp is there

my pwd returns this:

/home/[username]/Games/Romanovs-Vengeance/mods/rv/bits/projectiles

Because i git cloned the directory there.

So i tried playing allies and built the B2 bombers.
Once I ordered the bomber to attack, the game crashed again.

Loading mod: rv
[2021-10-30T17:46:35] Game started
Exception of type `System.IO.FileNotFoundException`: File not found: bits\projectiles\bomberbomb.shp
   at OpenRA.Mods.Common.Graphics.FileNotFoundSequence.OpenRA.Graphics.ISpriteSequence.get_Tick() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs:line 110
   at OpenRA.Graphics.Animation.PlaySequence(String sequenceName) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Graphics/Animation.cs:line 122
   at OpenRA.Graphics.Animation.PlayRepeating(String sequenceName) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Graphics/Animation.cs:line 137
   at OpenRA.Mods.Common.Projectiles.GravityBomb..ctor(GravityBombInfo info, ProjectileArgs args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Projectiles/GravityBomb.cs:line 90
   at OpenRA.Mods.Common.Projectiles.GravityBombInfo.Create(ProjectileArgs args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Projectiles/GravityBomb.cs:line 56
   at OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass34_0.<FireBarrel>b__2() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 330
   at OpenRA.Mods.Common.Traits.Armament.FireBarrel(Actor self, IFacing facing, Target& target, Barrel barrel) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 326
   at OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target& target) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Armament.cs:line 259
   at OpenRA.Mods.Common.Traits.AttackBase.DoAttack(Actor self, Target& target) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs:line 171
   at OpenRA.Mods.Common.Traits.AttackFollow.Tick(Actor self) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs:line 155
   at OpenRA.TraitDictionary.TraitContainer`1.ApplyToAllTimed(Action`2 action, String text) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/TraitDictionary.cs:line 313
   at OpenRA.World.Tick() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/World.cs:line 429
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 628
   at OpenRA.Game.LogicTick() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 643
   at OpenRA.Game.Loop() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 810
   at OpenRA.Game.Run() in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 863
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 295
   at OpenRA.Launcher.Program.Main(String[] args) in /home/teddy0/Games/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

AL lib: ReleaseALC: 1 device not closed

So yes there is this bug at least on my setup.

Is the appimage more stable i suppose?

But if cloning the dev version works that will be great also! I cloned from the master branch.

**Comment by GraionDilach** [comment]
@MustaphaTR You're using slashes instead of backslashes in the bomberbomb YAML path.

**Comment by MustaphaTR** [comment]
@GraionDilach Thanks.

@theodoreOnzGit I've fixed what Graion said, can you pull and test again by attacking with a B2.

**Comment by theodoreOnzGit** [comment]
Hello @MustaphaTR 

I have pulled from the git repo and rebuilt. B2s are now able to work without crashing.
Thank you!
