### ISSUE TITLE
report a serious bug

### ISSUE THREAD

**Issue by handht** [MustaphaTR/Romanovs-Vengeance#83]
report a serious bug
report a serious bug
report a serious bug
Say important things 3 times

I found a serious bug and hope you guys fix it in time
We play this game, the computer CPU is Huawei Kunpeng 920, the operating system is UOS, I compiled the program myself.
5 of us, 2V3, every game will suddenly close the game program during the game.
I found the log of the error, and I will report it to you.
If you want to contact me, please email: 272453823@qq.com

The following is the error log:
log 1:
OpenRA engine version 108b65e
Red Alert 2: Romanov's Vengeance mod version {DEV_VERSION}
on map 716cfac03cb21427fb709b4f74d2c4cc590753da (DEFCON 6 by Westwood Studios, ZxGanon).
Date: 2022-05-17 04:44:22Z
Operating System: Linux (Unix 4.19.0.64)
Runtime Version: .NET CLR 6.0.5
Exception of type `System.InvalidOperationException`: Out of sync in frame 16137.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 77
   at OpenRA.Network.OrderManager.ReceiveSync(ValueTuple`3 sync) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 155
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 309
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 205
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 623
   at OpenRA.Game.LogicTick() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 638
   at OpenRA.Game.Loop() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 801
   at OpenRA.Game.Run() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 851
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 293
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

Log 2:
OpenRA engine version 108b65e
Red Alert 2: Romanov's Vengeance mod version {DEV_VERSION}
on map 60df2c379affef9322382e0e68a529d39aa31c9f (Cold Circuit by Janitor).
Date: 2022-05-17 05:17:16Z
Operating System: Linux (Unix 4.19.0.64)
Runtime Version: .NET CLR 6.0.5
Exception of type `System.InvalidOperationException`: Out of sync in frame 23712.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 77
   at OpenRA.Network.OrderManager.ReceiveSync(ValueTuple`3 sync) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 155
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 309
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 205
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 623
   at OpenRA.Game.LogicTick() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 638
   at OpenRA.Game.Loop() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 801
   at OpenRA.Game.Run() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 851
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 293
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

Log3:
OpenRA engine version 108b65e
Red Alert 2: Romanov's Vengeance mod version {DEV_VERSION}
on map c025c46fe9bd7803fbf70206c8b19ace9670b644 (Snow Patrol by WavePy).
Date: 2022-05-17 05:24:58Z
Operating System: Linux (Unix 4.19.0.64)
Runtime Version: .NET CLR 6.0.5
Exception of type `System.InvalidOperationException`: Out of sync in frame 12192.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 77
   at OpenRA.Network.OrderManager.ReceiveSync(ValueTuple`3 sync) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 155
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 309
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 205
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 623
   at OpenRA.Game.LogicTick() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 638
   at OpenRA.Game.Loop() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 801
   at OpenRA.Game.Run() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 851
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 293
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

Log4:
OpenRA engine version 108b65e
Red Alert 2: Romanov's Vengeance mod version {DEV_VERSION}
on map ff1940c0f3e0c7d47adfd322983241a78661d355 (Tournament Highlands by Nah).
Date: 2022-05-17 06:21:29Z
Operating System: Linux (Unix 4.19.0.64)
Runtime Version: .NET CLR 6.0.5
Exception of type `System.InvalidOperationException`: Out of sync in frame 27460.
 Compare syncreport.log with other players.
   at OpenRA.Network.OrderManager.OutOfSync(Int32 frame) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 77
   at OpenRA.Network.OrderManager.ReceiveSync(ValueTuple`3 sync) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/OrderManager.cs:line 155
   at OpenRA.Network.NetworkConnection.OpenRA.Network.IConnection.Receive(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Network/Connection.cs:line 295
   at OpenRA.Sync.<>c__DisplayClass13_0.<RunUnsynced>b__0() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 167
   at OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 205
   at OpenRA.Sync.RunUnsynced(World world, Action fn) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Sync.cs:line 168
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 623
   at OpenRA.Game.LogicTick() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 638
   at OpenRA.Game.Loop() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 801
   at OpenRA.Game.Run() in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 851
   at OpenRA.Game.InitializeAndRun(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Game/Game.cs:line 293
   at OpenRA.Launcher.Program.Main(String[] args) in /home/user/Downloads/Romanovs-Vengeance/engine/OpenRA.Launcher/Program.cs:line 32

**Comment by dnqbob** [comment]
This may be fixed by https://github.com/MustaphaTR/OpenRA/pull/70

Sync problem is always hard to solve due to lack of sync-report if you did not turn on  sync-report recording
