### ISSUE TITLE
Game Crashing when joining online game.

### ISSUE THREAD

**Issue by kolsen** [MustaphaTR/Romanovs-Vengeance#92]
User is getting this crash when starting a skirmish or joining a hosted game.

OpenRA engine version 6ea4490
Red Alert 2: Romanov's Vengeance mod version playtest-20220707
on map d842fb8959f49beacbf0c028d2bc6ec99f69de21 (Billy Middlewins by Morton).
Date: 2022-09-15 04:33:12Z
Operating System: Windows (Microsoft Windows NT 10.0.19044.0)
Runtime Version: .NET CLR 6.0.6
Exception of type System.IO.InvalidDataException: Non-power-of-two array 768x192
   at OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height)
   at OpenRA.Platforms.Default.ThreadedTexture.<>cDisplayClass12_0.<.ctor>b6(Object tuple)
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Execute()
--- End of stack trace from previous location ---
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.Message.Result()
   at OpenRA.Platforms.Default.ThreadedGraphicsContext.RunMessage(Message message)
   at OpenRA.Platforms.Default.ThreadedTexture.SetData(Byte[] colors, Int32 width, Int32 height)
   at OpenRA.Graphics.Sheet.GetTexture()
   at OpenRA.Graphics.Sheet.ReleaseBuffer()
   at OpenRA.Graphics.Sheet..ctor(SheetType type, Stream stream)
   at OpenRA.Graphics.ChromeProvider.SheetForCollection(Collection c)
   at OpenRA.Graphics.ChromeProvider.GetImage(String collectionName, String imageName)
   at OpenRA.Mods.Common.Widgets.ImageWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.WindowsLauncher.RunGame(String[] args)

**Comment by kolsen** [comment]
User got it working in Windowed mode

**Comment by MustaphaTR** [comment]
Looks like the issue related to Selection UI icons when 3x sized ones are used on higher resolution monitors. Which is already fixed in the dev version. Apart from windowed, reducing the UI Scale option should fix this crash for now too.
